pipeline {
  agent none
  stages {
    stage('Build') {
      agent {
        docker { image 'node:16-alpine' }
      } 
      steps {
        sh 'node --version'
      }
    }  
    stage('DB'){
      agent {
        docker { image 'mysql:latest'}
      }
      steps {
        sh 'echo hi'
      }  
    }
  }    
}
